{{- if .Values.couchbase.password }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "couchbase-exporter.fullname" . }}
type: Opaque
data:
  password: {{ .Values.couchbase.password | b64enc | quote }}
{{- end }}